Update trunk-deployment.yml

diff --git a/.github/workflows/trunk-deployment.yml b/.github/workflows/trunk-deployment.yml
--- a/.github/workflows/trunk-deployment.yml
+++ b/.github/workflows/trunk-deployment.yml
@@ -4,13 +4,16 @@ concurrency: trunk-deployment  # move to deployment job if we need to queue up a
 on:
   workflow_run:
     workflows: ['Maven CICD Pipeline']
-    types: [completed]
+    types:
+      - completed
+    branches:
+      - master
 permissions:
   contents: read
   actions: read # allow access to other job artifacts with GITHUB_TOKEN
 jobs:
   deployment:
-    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
     environment: trunk
     steps:
@@ -18,6 +21,20 @@ jobs:
       # for security reasons
       - name: Checkout core
         uses: actions/checkout@v4
+      - name: Get the latest commit SHA from master
+        id: latest_commit
+        run: |
+          echo "TRIGGER_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
+          LATEST_SHA=$(git rev-parse origin/master)
+          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_ENV
+          echo "The latest commit SHA is $LATEST_SHA"
+
+      - name: Check if triggered by the latest commit
+        if: env.TRIGGER_SHA != env.LATEST_SHA
+        run: |
+          echo "This workflow was triggered by an old commit. Latest commit SHA: $LATEST_SHA, Trigger commit SHA: $TRIGGER_SHA"
+          exit 1  # This fails the step and cancels the deployment
+
       - name: Get the original commit SHA
         run:  |
           echo "The original commit SHA is ${{ github.event.workflow_run.head_sha }}"
@@ -47,4 +64,3 @@ jobs:
           SLACK_FOOTER: ""
           SLACK_ICON: https://avatars.githubusercontent.com/u/1005263?s=200&v=4
           SLACK_MESSAGE: "This automated script is happy to announce that a new docker image has been built for *master* with tags: [${{ steps.docker_build.outputs.tags }}] :docker:"
-
